### ISSUE TITLE
Add background for datepicker popup

### ISSUE THREAD

**Issue by pi0** [IBM/vue-a11y-calendar#11]
Currently, date picker body has a transparent background, resulting in a bad display:

![image](https://user-images.githubusercontent.com/5158436/31030103-ff07b374-a560-11e7-92a7-9172a998fd4e.png)

It may be replaced with a white bg color:

![image](https://user-images.githubusercontent.com/5158436/31030119-0f210c06-a561-11e7-9dd9-4b05ac6b7c6e.png)

**Comment by Snugug** [comment]
Weird! I thought I had fixed that!
