### ISSUE TITLE
Unable to click on date buttons in Firefox or Safari 

### ISSUE THREAD

**Issue by traveish** [IBM/vue-a11y-calendar#20]
When trying to click on a specific date when using Firefox or Safari (on macOS for me), only the outermost wrapper `.calendar` element is receiving focus.  It is working as expected in the Chrome browser.  

I have tried a few things, but without luck quite yet.  Tried removing the `role="application"` attribute from the `.calendar` container, and `tabindex="-1"`

I very much appreciate this component, it makes for amazing case of a11y-first design and fantastic examples for documentation and repository design.  I am looking forward to building upon and contributing back to it in the near future.

**Comment by traveish** [comment]
Update: Found that the `select()` method is checking for `'calendar__date'`, but Safari/FireFox are triggering the click event on the BUTTON element itself (not the TD cell container) ... So, I will be adding some logic in there to check for: `"calendar__link"` and make a pull-request.

**Comment by Snugug** [comment]
Thanks so much for the kind words and digging in to this!

**Comment by Snugug** [comment]
What may be the easiest path forward is to use [`closest`](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest) to find the closest `calendar__date`. If `calendar__link` triggers it, it'll walk up the DOM to find `calendar__date`, but if `calendar__date` triggers it, it'll all work as expected.
