### ISSUE TITLE
Ability to assign a date to datepicker

### ISSUE THREAD

**Issue by thisisjoshhansen** [IBM/vue-a11y-calendar#26]
At times, the date from datepicker may need to be updated programmatically. At the moment, there does not seem to be a way to do this.

**Comment by thisisjoshhansen** [comment]
What about this pattern?
https://vuejs.org/v2/guide/forms.html

e.g.:
`<datepicker v-model="someDateObject"></datepicker>`

**Comment by Snugug** [comment]
Yes, that was going to be my recommendation. However, there are actually 4 inputs here; the localized date, and then three hidden structured inputs for day, month, and year in numeric form, non-localized. `someDateObject` would need an object with those properties.
