### ISSUE TITLE
Add live demo

### ISSUE THREAD

**Issue by Snugug** [IBM/vue-a11y-calendar#4]
Put a live demo up!

## Requirements

**Needs**
* Display default components, as well as components with props changed to show different states
  * Source code for different states should be obvious for users coming in to view source
  * Show documentation in-browser for the changes to state that have happened
* Include description of the particular state
* Show any events that are generated
* Limited additional code needed to work
* Deploy to GitHub Pages
* Passes linting and aligns with existing code standards in the codebase
* Either entirely neutral (black/white/grey) or custom styling; no CSS frameworks used
* Ability to show landing page with documentation from README
* Accessible

**Nice to Have**
* Server-side rendering w/client-side pickup
* Ability to show routing actions
* Integrates with JSDoc to display code documentation along with component documentation
* Can easily integrate with automated testing. [AVA](https://github.com/avajs/ava) and [Nightwatch](http://nightwatchjs.org/) preferred.

**Comment by pi0** [comment]
@Snugug I can help for that if you are interested

**Comment by brianjorden** [comment]
Just was looking at this and the related pull request. First off, kudos (praise) to both of you for a nice to see thoughtful back and forth on this topic.

The PR did actually let me see the semi-live  example. Based on the ton of Twitter activity around this right now, I might suggest a short term option. Might drive up interest (and future contributions) by just throwing even a screenshot or two into the readme page until a live demo version is sorted out.

I'm just on my phone at the moment, but if no one has had a chance yet, I'll try to do a PR for this tonight or tomorrow.

**Comment by Snugug** [comment]
@brianjorden Thanks for the feedback! Working with @pi0 to get #6 merged for an initial demo then going to work on getting a full demo up and running
