### ISSUE TITLE
Documentation: unnecessary alias for node_modules

### ISSUE THREAD

**Issue by nicolaspayot** [IBM/vue-a11y-calendar#5]
Hi, just came across your repo. I read the doc and I was wondering why you need to add an alias to resolve `node_modules` path, in the Webpack configuration.

`import calendar from 'vue-a11y-calendar/calendar'` should work, shouldn't it?

**Comment by Snugug** [comment]
Fair point, actually! It shouldn't. I don't know why I wound up adding that.
